#!/bin/bash

if [[ "${DOCKER_TAG}" =~ ^([0-9]{8})-(.+)$ ]]
then
	portage=${BASH_REMATCH[1]}
	flavor=${BASH_REMATCH[2]}

	docker build --build-arg portage=${portage} --build-arg flavor=${flavor} -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} .
fi
